# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d6262a6f4a3f77eae6df6d89a6359dc11be61f7e5c5460fccbbd6e3ce706d064914957097aa00ad16b50c4f76fb15a761f08b1a0f919071e9fb7aefed41e138

test:
  secret_key_base: 383f5a9ca596fb760a15bef4da95db308ce2d173919f2b4670a141ce8d2511fb077ae2cd1d82dc13466c8bdf387ff6f2ecf2a406a94a45f1dda914865a671371

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
